name: Build and test recrep

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and run available unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
